/**
 * utils.js
 * Shared utilities: storage, export (Markdown, PDF, TXT), formatting, toast.
 */

/* ═══════════════════════════════════════════════
   STORAGE UTILITIES
═══════════════════════════════════════════════ */
const Storage = {
  /**
   * Save a completed meeting session.
   * @param {Object} session - { id, title, date, duration, transcript, notes }
   */
  async saveSession(session) {
    const { sessions = [] } = await chrome.storage.local.get('sessions');
    sessions.unshift(session); // newest first
    // Keep only last 30 sessions
    const trimmed = sessions.slice(0, 30);
    await chrome.storage.local.set({ sessions: trimmed });
    return session;
  },

  async getSessions() {
    const { sessions = [] } = await chrome.storage.local.get('sessions');
    return sessions;
  },

  async deleteSession(id) {
    const { sessions = [] } = await chrome.storage.local.get('sessions');
    const updated = sessions.filter(s => s.id !== id);
    await chrome.storage.local.set({ sessions: updated });
  },

  async clearSessions() {
    await chrome.storage.local.set({ sessions: [] });
  },

  async saveSettings(settings) {
    await chrome.storage.local.set({ settings });
  },

  async getSettings() {
    const { settings = {} } = await chrome.storage.local.get('settings');
    return settings;
  },
};

/* ═══════════════════════════════════════════════
   EXPORT UTILITIES
═══════════════════════════════════════════════ */
const Exporter = {
  /**
   * Convert notes object to Markdown string.
   */
  toMarkdown(session) {
    const n = session.notes || {};
    const lines = [
      `# ${n.title || session.title || 'Meeting Notes'}`,
      `> *Recorded on ${formatDate(session.date)} · Duration: ${formatDuration(session.duration)}*`,
      '',
      '## Summary',
      n.summary || 'No summary available.',
      '',
    ];

    if (n.keyPoints?.length) {
      lines.push('## Key Points');
      n.keyPoints.forEach(p => lines.push(`- ${p}`));
      lines.push('');
    }

    if (n.concepts?.length) {
      lines.push('## Important Concepts');
      n.concepts.forEach(c => lines.push(`- **${c}**`));
      lines.push('');
    }

    if (n.actionItems?.length) {
      lines.push('## Action Items');
      n.actionItems.forEach(a => lines.push(`- [ ] ${a}`));
      lines.push('');
    }

    if (n.decisions?.length) {
      lines.push('## Decisions Made');
      n.decisions.forEach(d => lines.push(`- ${d}`));
      lines.push('');
    }

    if (n.tasks?.length) {
      lines.push('## Tasks');
      lines.push('| Task | Assignee | Deadline |');
      lines.push('|------|----------|----------|');
      n.tasks.forEach(t => lines.push(`| ${t.task} | ${t.assignee || '—'} | ${t.deadline || '—'} |`));
      lines.push('');
    }

    if (n.deadlines?.length) {
      lines.push('## Deadlines');
      n.deadlines.forEach(d => lines.push(`- **${d.item}** — ${d.date}`));
      lines.push('');
    }

    if (n.followUps?.length) {
      lines.push('## Follow-ups');
      n.followUps.forEach(f => lines.push(`- ${f}`));
      lines.push('');
    }

    if (n.questions?.length) {
      lines.push('## Questions Discussed');
      n.questions.forEach(q => lines.push(`- ${q}`));
      lines.push('');
    }

    lines.push('---');
    lines.push('## Full Transcript');
    lines.push('');
    lines.push(session.transcript || 'No transcript available.');
    lines.push('');
    lines.push(`*Generated by NoteScribe AI*`);

    return lines.join('\n');
  },

  /**
   * Download a text string as a file.
   */
  downloadText(content, filename) {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  },

  /**
   * Export as Markdown (.md) file.
   */
  exportMarkdown(session) {
    const md       = this.toMarkdown(session);
    const filename = `notescribe-${slugify(session.title || 'meeting')}-${formatDateSlug(session.date)}.md`;
    this.downloadText(md, filename);
  },

  /**
   * Export as plain text transcript.
   */
  exportTranscript(session) {
    const filename = `transcript-${slugify(session.title || 'meeting')}-${formatDateSlug(session.date)}.txt`;
    this.downloadText(session.transcript || '', filename);
  },

  /**
   * Export as PDF using print dialog.
   * Opens a styled page and triggers window.print().
   */
  exportPDF(session) {
    const md    = this.toMarkdown(session);
    const html  = this._markdownToHTML(md, session);
    const win   = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); }, 500);
  },

  /** Minimal MD → HTML for PDF export */
  _markdownToHTML(md, session) {
    const body = md
      .replace(/^# (.+)$/gm,    '<h1>$1</h1>')
      .replace(/^## (.+)$/gm,   '<h2>$1</h2>')
      .replace(/^> \*(.+)\*$/gm,'<p class="meta">$1</p>')
      .replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>')
      .replace(/^- \[ \] (.+)$/gm, '<li class="task">☐ $1</li>')
      .replace(/^- (.+)$/gm,    '<li>$1</li>')
      .replace(/^---$/gm,       '<hr/>')
      .replace(/\n\n/g,         '</p><p>')
      .replace(/^(<h|<hr|<li|<p class)/gm, '$1');

    return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${session.title || 'NoteScribe AI'}</title>
<style>
  body{font-family:Georgia,serif;max-width:800px;margin:40px auto;padding:0 24px;color:#1a1a1a;line-height:1.7}
  h1{font-size:24px;margin-bottom:4px;color:#0e0e0e}
  h2{font-size:16px;margin:22px 0 8px;color:#444;text-transform:uppercase;letter-spacing:.5px;border-bottom:1px solid #eee;padding-bottom:4px}
  .meta{color:#888;font-style:italic;font-size:13px;margin-bottom:20px}
  li{margin-bottom:4px}
  li.task{list-style:none;margin-left:-16px}
  hr{border:none;border-top:1px solid #eee;margin:24px 0}
  pre{background:#f5f5f5;padding:12px;border-radius:4px;font-size:13px;overflow:auto}
  @media print{body{margin:20px}}
</style>
</head>
<body>${body}</body>
</html>`;
  },

  /** Copy notes + transcript to clipboard */
  async copyToClipboard(session) {
    const md = this.toMarkdown(session);
    await navigator.clipboard.writeText(md);
  },
};

/* ═══════════════════════════════════════════════
   TOAST NOTIFICATIONS
═══════════════════════════════════════════════ */
let toastTimeout = null;

function showToast(message, duration = 2500) {
  const el = document.getElementById('toast');
  if (!el) return;
  el.textContent = message;
  el.classList.remove('hidden');
  clearTimeout(toastTimeout);
  toastTimeout = setTimeout(() => el.classList.add('hidden'), duration);
}

/* ═══════════════════════════════════════════════
   DATE / STRING HELPERS
═══════════════════════════════════════════════ */
function formatDate(dateStr) {
  if (!dateStr) return '—';
  return new Date(dateStr).toLocaleDateString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

function formatDateSlug(dateStr) {
  if (!dateStr) return Date.now().toString();
  return new Date(dateStr).toISOString().slice(0, 10);
}

function formatDuration(seconds) {
  if (!seconds) return '0s';
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
}

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
}

function generateId() {
  return `ns_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
}

function countWords(text) {
  return text ? text.split(/\s+/).filter(Boolean).length : 0;
}

/* ═══════════════════════════════════════════════
   SEARCH UTILITY
═══════════════════════════════════════════════ */
function searchSessions(sessions, query) {
  if (!query.trim()) return sessions;
  const q = query.toLowerCase();
  return sessions.filter(s =>
    (s.title      || '').toLowerCase().includes(q) ||
    (s.transcript || '').toLowerCase().includes(q)
  );
}

// Expose globals
window.Storage     = Storage;
window.Exporter    = Exporter;
window.showToast   = showToast;
window.formatDate  = formatDate;
window.formatDuration = formatDuration;
window.generateId  = generateId;
window.countWords  = countWords;
window.searchSessions = searchSessions;
